### ISSUE TITLE
Data cube from Ginga to Glue gives IndexError

### ISSUE THREAD

**Issue by pllim** [ejeschke/glue-ginga#25]
Workflow:

1. Start Ginga.
2. Start Glue from Ginga's Glue plugin.
3. Load "ngc6946.fits" (https://stsci.box.com/s/tg6m48hccnmn8jjs3447e0yuillz56ld) in Ginga.
4. Press "Put Data" button on Glue plugin in Ginga.
5. The file is now listed in Glue's left menu but inaccessible.

```python
Traceback (most recent call last):
  File ".../glue/core/application_base.py", line 25, in wrapper
    return func(*args, **kwargs)
  File ".../glue/core/application_base.py", line 197, in add_data
    self.add_datasets(self.data_collection, datasets)
  File ".../glue/core/application_base.py", line 250, in add_datasets
    data_collection.extend(datasets)
  File ".../glue/core/data_collection.py", line 84, in extend
    [self.append(d) for d in data]
  File ".../glue/core/data_collection.py", line 84, in <listcomp>
    [self.append(d) for d in data]
  File ".../glue/core/data_collection.py", line 75, in append
    self._sync_link_manager()
  File ".../glue/core/data_collection.py", line 111, in _sync_link_manager
    for link in d.coordinate_links:
  File ".../glue/core/data.py", line 586, in coordinate_links
    self.coords, i)
  File ".../glue/core/component_link.py", line 317, in __init__
    comp_from = [comp_from[i] for i in self.from_needed]
  File ".../glue/core/component_link.py", line 317, in <listcomp>
    comp_from = [comp_from[i] for i in self.from_needed]
IndexError: list index out of range
```

**Comment by ejeschke** [comment]
@pllim, we may need to rework the way the data is put into the glue dataset when it is transferred.  In the case of a cube or higher dimension, we probably need to pass more than just the current slice so that the metadata matches up.  I haven't tested this yet, but you probably can replace the `image.get_data()` [here](https://github.com/ejeschke/glue-ginga/blob/master/glue_ginga/plugins/Glue.py#L238) with something like `image.get_mddata()`.

**Comment by ejeschke** [comment]
I'll hold off on the release until we check whether this simple fix (or something like it) does the trick.

**Comment by ejeschke** [comment]
That worked, then, @pllim?

**Comment by pllim** [comment]
@ejeschke , unfortunately only partly. See https://github.com/ejeschke/glue-ginga/pull/26#issuecomment-326671264

Also I uncovered #27 while testing #26.
